swagger:
  base:
    package: com.institute.bi.tierc.user
  api:
    title: Baghant Institute User Service
    description: Baghant Institute Tier-C User Service
    version: '@project.version@'
    termsOfServiceUrl: http://swagger.io
    contact: bijendrakrguptaitfiem@gmail.com
    license: Baghant
    licenseUrl: https://en.wikipedia.org/wiki/Proprietary_software
server:
  port: 9089
logging:
  level:
    org.springframework: ERROR
    com.mkyong: DEBUG
  pattern:
    console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'
    file: '%d %p %c{1.} [%t] %m%n'
  file: app.log
spring:
  application:
    name: spring-cloud-eureka-client
#eureka:
#  instance:
#   hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8765/eureka/
database:
  hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
    showSql: true
    formatSql: true
    hbm2ddlAuto: update
    secondLevelCache: true
    cacheRegionFactoryClass: org.hibernate.cache.ehcache.EhCacheRegionFactory
    queryCache: true
  mysql:
    driverClass: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/baghant
    userName: root
    password: root